
services:
  postgres:
    image: timescale/timescaledb:2.21.2-pg16
    ports:
    - '5432:5432'
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgres-data: {}