
services:
  postgres:
    image: timescale/timescaledb:2.21.2-pg16
    ports:
    - '5432:5432'
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  grafana:
    image: grafana/grafana:12.0.4
    depends_on:
    - postgres
    ports:
    - '3000:3000'
    volumes:
    - grafana-data:/var/lib/grafana


volumes:
  postgres-data: {}
  grafana-data: {}